#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyPantry.Resource", IsApplication=true)]

namespace MyPantry
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::MyPantry.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::MyPantry.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::MyPantry.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040006
			public const int ajouter = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int category = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int cell = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int contentFrame = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int del = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int image = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int productList = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int supprimer = 2130968583;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int FoodDescriptor = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ListItem = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Main = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int zxingscanneractivitylayout = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int zxingscannerfragmentlayout = 2130837508;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
